export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>MyResumeSiteNg</title>
  <base href="/my-resume-site-ng/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<style>body{margin:0;font-family:Segoe UI,Tahoma,Geneva,Verdana,sans-serif;background-color:#f8f9fa;color:#333;line-height:1.6}h1{color:#0d6efd;font-weight:700}ul{padding-left:1rem;list-style-type:none}ul li:before{color:#0d6efd;font-weight:700}.navbar{background-color:#212529;padding:1rem 0}.navbar .container{display:flex;justify-content:space-between;align-items:center;max-width:1000px;margin:0 auto;padding:0 1rem}.navbar .logo{color:#fff;font-weight:700;text-decoration:none;font-size:1.5rem}.navbar ul{display:flex;gap:1rem;margin:0;padding:0}.navbar ul li a{color:#fff;text-decoration:none;font-weight:500;transition:color .3s}.navbar ul li a:hover,.navbar ul li a.active{color:#0d6efd}.container{max-width:1000px;margin:0 auto;padding:2rem 1rem}.text-center{text-align:center}footer{background-color:#212529;color:#fff;text-align:center;padding:1rem 0;margin-top:2rem}.gallery{display:flex;flex-wrap:wrap;gap:1rem;justify-content:center;margin-top:2rem}.gallery img{width:300px;height:200px;object-fit:cover;border-radius:10px;transition:transform .3s,box-shadow .3s}.gallery img:hover{transform:scale(1.05);box-shadow:0 10px 20px #0003}
</style><link rel="stylesheet" href="styles-BYAO45LN.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles-BYAO45LN.css"></noscript></head>
<body>
  <app-root ng-version="21.0.0" ng-server-context="ssg"><nav class="navbar"><div class="container"><a routerlink="/" class="logo" href="/my-resume-site-ng/">My Resume</a><ul class="nav-links"><li><a routerlink="/" routerlinkactive="active" href="/my-resume-site-ng/" class>Home</a></li><li><a routerlink="/hobby" routerlinkactive="active" href="/my-resume-site-ng/hobby" class>Hobbies</a></li><li><a routerlink="/contact" routerlinkactive="active" href="/my-resume-site-ng/contact" class>Contact</a></li><li><a routerlink="/gallery" routerlinkactive="active" href="/my-resume-site-ng/gallery" class="active">Gallery</a></li></ul></div></nav><router-outlet></router-outlet><app-gallery><main class="container"><div class="text-center"><h1>My Photo Gallery</h1></div><div class="gallery"><img src="image/image2.jpeg" alt="Gallery image"><img src="image/image3.jpeg" alt="Gallery image"><img src="image/image4.jpeg" alt="Gallery image"></div></main></app-gallery><!----><footer><p>© 2025 Yon Yu Ki. All Rights Reserved.</p></footer></app-root>
<script src="main-R66VMSHQ.js" type="module"></script>

</body></html>`;